/**
 * Expo config plugin: drop the network permissions from release builds.
 *
 * KidsDoodle is entirely offline — the JS bundle is compiled into the APK and
 * nothing in the app makes a network request. INTERNET is only needed in debug
 * builds so the device can reach the Metro dev server, and ACCESS_NETWORK_STATE
 * is merged in from React Native core's own library manifest for the networking
 * stack this app never uses.
 *
 * `android.blockedPermissions` in app.json can't express "debug only": it edits
 * the main manifest, which both build types inherit. Writing a release-only
 * source set manifest is the mechanism that can, so the shipped APK declares no
 * network permission at all while `expo run:android` keeps working.
 *
 * That file is not part of the Expo template, so this plugin recreates it on
 * every prebuild rather than leaving it to be silently lost.
 */
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const RELEASE_MANIFEST = `<!--
  Generated by plugins/withOfflineReleaseManifest.js — do not edit by hand.

  Release-only overlay: KidsDoodle makes no network requests, so the released
  APK declares no network permissions at all. Both are kept in debug builds —
  INTERNET so the device can reach the Metro dev server, ACCESS_NETWORK_STATE
  because React Native core's manifest contributes it.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" tools:node="remove"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove"/>
</manifest>
`;

module.exports = function withOfflineReleaseManifest(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'release');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'AndroidManifest.xml'), RELEASE_MANIFEST);
      return cfg;
    },
  ]);
};
