#!/usr/bin/env bash
# Verifies the per-ABI release APKs before anything is published.
#
# Used by both workflows: ci.yml runs it without --expect-cert (it builds
# without a keystore, exactly as F-Droid's buildserver does), release.yml runs
# it with the pinned certificate.
#
# Checks, per APK:
#   * exactly one ABI            — a universal build would blow the size limit
#   * the exact permission set   — a dependency must not reintroduce a permission
#   * size under the size budget — keeps the download small (see PACKAGING.md)
#   * the signing certificate    — only when --expect-cert is given
set -euo pipefail

APK_DIR=${1:?usage: scripts/check-release-apks.sh <apk-dir> [--expect-cert <sha256>]}
shift
EXPECT_CERT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --expect-cert) EXPECT_CERT="${2:?--expect-cert needs a value}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# Per-APK size budget. This began as IzzyOnDroid's hard limit; that path is
# closed (see docs/PACKAGING.md), but the number is kept as a regression guard
# so a future dependency cannot quietly undo the ABI split, the minification or
# the library compression that took the universal v1.0.0 APK from 94 MB to 18.
MAX_APK_BYTES=${MAX_APK_BYTES:-30000000}

# This app requests no Android permission at all. The only entry left is
# DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION, generated by AndroidX core and
# namespaced to our own package with protectionLevel="signature": it is
# app-private, grants nothing to other apps, is not shown to users, and removing
# it would break ContextCompat.registerReceiver.
EXPECTED_PERMISSIONS='com.kidsdoodle.app.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'

EXPECTED_ABI_COUNT=$(node -p \
  "require('$(cd "$(dirname "$0")/.." && pwd)/plugins/withAbiSplits.js').ABIS.length")

BUILD_TOOLS="$(ls -d "${ANDROID_HOME:?ANDROID_HOME is not set}"/build-tools/* | sort -V | tail -1)"

shopt -s nullglob
APKS=("$APK_DIR"/*.apk)
if [ "${#APKS[@]}" -ne "$EXPECTED_ABI_COUNT" ]; then
  echo "::error::Expected ${EXPECTED_ABI_COUNT} per-ABI APKs in ${APK_DIR}, found ${#APKS[@]}."
  printf '  %s\n' "${APKS[@]:-(none)}"
  exit 1
fi

fail=0
for APK in "${APKS[@]}"; do
  NAME="$(basename "$APK")"
  echo "::group::${NAME}"

  ABIS="$(unzip -Z1 "$APK" 'lib/*' 2>/dev/null | cut -d/ -f2 | sort -u)"
  ABI_COUNT="$(printf '%s' "$ABIS" | grep -c . || true)"
  if [ "$ABI_COUNT" -ne 1 ]; then
    echo "::error::${NAME} contains ${ABI_COUNT} ABIs, expected exactly 1: $(echo $ABIS)"
    fail=1
  fi

  ACTUAL_PERMISSIONS="$("$BUILD_TOOLS/aapt2" dump permissions "$APK" \
                        | sed -n "s/^uses-permission: name='\(.*\)'$/\1/p" | sort)"
  if [ "$ACTUAL_PERMISSIONS" != "$EXPECTED_PERMISSIONS" ]; then
    echo "::error::${NAME} has an unexpected permission set."
    echo "Expected:"; echo "$EXPECTED_PERMISSIONS"
    echo "Actual:";   echo "${ACTUAL_PERMISSIONS:-(none)}"
    echo "INTERNET or ACCESS_NETWORK_STATE here means"
    echo "plugins/withOfflineReleaseManifest.js did not apply. VIBRATE here"
    echo "means something reintroduced android.permission.VIBRATE, which"
    echo "app.json blocks."
    fail=1
  fi

  SIZE="$(stat -c%s "$APK")"
  if [ "$SIZE" -gt "$MAX_APK_BYTES" ]; then
    echo "::error::${NAME} is ${SIZE} bytes, over the ${MAX_APK_BYTES}-byte budget."
    fail=1
  fi

  CERT_NOTE=""
  if [ -n "$EXPECT_CERT" ]; then
    # Android identifies an app by package name + signing certificate, so an APK
    # signed with any other key is a different app to every device that already
    # has this one: users would have to uninstall and reinstall to update.
    CERTS="$("$BUILD_TOOLS/apksigner" verify --print-certs "$APK")"
    echo "$CERTS"

    # apksigner labels the signer by signature scheme and SDK range, not by
    # index: these APKs print "V2 Signer: certificate SHA-256 digest: ...", and
    # other combinations print "Signer #1 ..." or "Signer (minSdkVersion=24,
    # maxSdkVersion=...) #1 ...". Match only the part common to all of them —
    # anchoring on "Signer #1" yielded nothing and reported every correctly
    # signed APK as wrongly signed.
    ACTUAL_CERT="$(echo "$CERTS" \
      | sed -n 's/.*certificate SHA-256 digest: *//p' | head -1)"

    if [ -z "$ACTUAL_CERT" ]; then
      echo "::error::${NAME}: could not read a certificate digest from apksigner."
      echo "Its output is above; the parsing in this script needs updating."
      fail=1
    elif [ "$ACTUAL_CERT" != "$EXPECT_CERT" ]; then
      echo "::error::${NAME} is signed with the wrong key."
      echo "Expected certificate SHA-256: $EXPECT_CERT"
      echo "Actual certificate SHA-256:   $ACTUAL_CERT"
      if echo "$CERTS" | grep -q "CN=Android Debug"; then
        echo "It is the public debug key: the ANDROID_* secrets did not reach"
        echo "Gradle. Check they are set on this repository."
      fi
      fail=1
    else
      CERT_NOTE=", signed with the expected key"
    fi
  fi

  printf '%s: %s, %s MB%s\n' "$NAME" "${ABIS:-no native code}" \
    "$((SIZE / 1000000))" "$CERT_NOTE"
  echo "::endgroup::"
done

if [ "$fail" -ne 0 ]; then
  exit 1
fi
echo "OK — ${#APKS[@]} single-ABI APKs, each under $((MAX_APK_BYTES / 1000000)) MB, requesting no Android permission."
